"""Стартовый баланс нужен, чтобы прототип сразу был играбельным без админки."""

from app.domain.models import (
    AssetType,
    Bank,
    BusinessAsset,
    Company,
    FacilityOption,
    FactoryFormat,
    NpcStrategy,
    Product,
    ProductionRecipe,
    RawMaterial,
    RecipeInput,
    Region,
    Role,
    StoreFormat,
    StoreFormatOption,
    WarehouseFormat,
)

STORE_FORMATS: dict[StoreFormat, StoreFormatOption] = {
    StoreFormat.KIOSK: StoreFormatOption(
        store_format=StoreFormat.KIOSK,
        name="Киоск",
        capacity_units_per_day=600,
        fixed_cost_rub_per_day=25_000,
        build_cost_rub=1_200_000,
        storage_type="сухое",
        demand_multiplier=0.7,
    ),
    StoreFormat.CONVENIENCE: StoreFormatOption(
        store_format=StoreFormat.CONVENIENCE,
        name="Магазин у дома",
        capacity_units_per_day=1_800,
        fixed_cost_rub_per_day=75_000,
        build_cost_rub=4_500_000,
        storage_type="смешанное",
        demand_multiplier=1.0,
    ),
    StoreFormat.SUPERMARKET: StoreFormatOption(
        store_format=StoreFormat.SUPERMARKET,
        name="Супермаркет",
        capacity_units_per_day=5_000,
        fixed_cost_rub_per_day=180_000,
        build_cost_rub=14_000_000,
        storage_type="смешанное",
        demand_multiplier=1.5,
    ),
}

FACTORY_FORMATS: dict[str, FacilityOption] = {
    FactoryFormat.WORKSHOP.value: FacilityOption(
        asset_type=AssetType.FACTORY,
        tier=FactoryFormat.WORKSHOP.value,
        name="Цех",
        capacity_units_per_day=1_200,
        fixed_cost_rub_per_day=60_000,
        build_cost_rub=6_000_000,
        storage_type="производство",
        output_multiplier=0.85,
    ),
    FactoryFormat.PLANT.value: FacilityOption(
        asset_type=AssetType.FACTORY,
        tier=FactoryFormat.PLANT.value,
        name="Завод",
        capacity_units_per_day=2_500,
        fixed_cost_rub_per_day=125_000,
        build_cost_rub=16_000_000,
        storage_type="производство",
        output_multiplier=1.0,
    ),
    FactoryFormat.COMPLEX.value: FacilityOption(
        asset_type=AssetType.FACTORY,
        tier=FactoryFormat.COMPLEX.value,
        name="Комбинат",
        capacity_units_per_day=5_000,
        fixed_cost_rub_per_day=240_000,
        build_cost_rub=34_000_000,
        storage_type="производство",
        output_multiplier=1.15,
    ),
}

WAREHOUSE_FORMATS: dict[str, FacilityOption] = {
    WarehouseFormat.DEPOT.value: FacilityOption(
        asset_type=AssetType.WAREHOUSE,
        tier=WarehouseFormat.DEPOT.value,
        name="Склад",
        capacity_units_per_day=1_500,
        fixed_cost_rub_per_day=30_000,
        build_cost_rub=3_500_000,
        storage_type="смешанное",
        output_multiplier=0.85,
    ),
    WarehouseFormat.CENTER.value: FacilityOption(
        asset_type=AssetType.WAREHOUSE,
        tier=WarehouseFormat.CENTER.value,
        name="Распределительный центр",
        capacity_units_per_day=3_000,
        fixed_cost_rub_per_day=60_000,
        build_cost_rub=9_000_000,
        storage_type="смешанное",
        output_multiplier=1.0,
    ),
    WarehouseFormat.HUB.value: FacilityOption(
        asset_type=AssetType.WAREHOUSE,
        tier=WarehouseFormat.HUB.value,
        name="Логистический хаб",
        capacity_units_per_day=6_000,
        fixed_cost_rub_per_day=110_000,
        build_cost_rub=22_000_000,
        storage_type="смешанное",
        output_multiplier=1.20,
    ),
}

FACILITY_FORMATS: dict[AssetType, dict[str, FacilityOption]] = {
    AssetType.FACTORY: FACTORY_FORMATS,
    AssetType.WAREHOUSE: WAREHOUSE_FORMATS,
}

REGIONS: list[Region] = [
    Region(
        id="north",
        name="Североградский край",
        description="Холодный регион с дорогой логистикой и стабильным спросом.",
        demand_index=0.85,
        income_index=1.05,
        logistics_risk=0.35,
    ),
    Region(
        id="central",
        name="Центральная область",
        description="Крупнейший потребительский рынок с высокой конкуренцией.",
        demand_index=1.35,
        income_index=1.25,
        logistics_risk=0.12,
    ),
    Region(
        id="south",
        name="Южный округ",
        description="Аграрный регион с сезонностью овощей, фруктов и жары.",
        demand_index=1.05,
        income_index=0.95,
        logistics_risk=0.18,
    ),
    Region(
        id="volga",
        name="Приволжский промышленный пояс",
        description="Производственная база с развитой дорожной сетью.",
        demand_index=1.0,
        income_index=1.0,
        logistics_risk=0.1,
    ),
    Region(
        id="east_port",
        name="Восточный портовый край",
        description="Портовый регион с импортом и длинными транспортными плечами.",
        demand_index=0.9,
        income_index=1.1,
        logistics_risk=0.28,
    ),
]

PRODUCTS: list[Product] = [
    Product(
        id="bread",
        name="Хлеб",
        storage="обычное",
        shelf_life_days=2,
        base_price_rub=65,
        base_daily_demand=900,
    ),
    Product(
        id="milk",
        name="Молоко",
        storage="холодильник",
        shelf_life_days=7,
        base_price_rub=95,
        base_daily_demand=760,
    ),
    Product(
        id="yogurt",
        name="Кефир/йогурт",
        storage="холодильник",
        shelf_life_days=10,
        base_price_rub=85,
        base_daily_demand=520,
    ),
    Product(
        id="cheese",
        name="Сыр",
        storage="холодильник",
        shelf_life_days=30,
        base_price_rub=420,
        base_daily_demand=210,
    ),
    Product(
        id="eggs",
        name="Яйца",
        storage="прохладное",
        shelf_life_days=25,
        base_price_rub=130,
        base_daily_demand=480,
    ),
    Product(
        id="chicken",
        name="Курица",
        storage="холодильник",
        shelf_life_days=5,
        base_price_rub=280,
        base_daily_demand=360,
    ),
    Product(
        id="meat",
        name="Мясо",
        storage="холодильник",
        shelf_life_days=5,
        base_price_rub=560,
        base_daily_demand=240,
    ),
    Product(
        id="sausage",
        name="Колбаса",
        storage="холодильник",
        shelf_life_days=20,
        base_price_rub=390,
        base_daily_demand=260,
    ),
    Product(
        id="fish",
        name="Рыба",
        storage="морозильник",
        shelf_life_days=12,
        base_price_rub=520,
        base_daily_demand=180,
    ),
    Product(
        id="vegetables",
        name="Овощи",
        storage="прохладное",
        shelf_life_days=7,
        base_price_rub=110,
        base_daily_demand=680,
    ),
    Product(
        id="fruits",
        name="Фрукты",
        storage="прохладное",
        shelf_life_days=7,
        base_price_rub=150,
        base_daily_demand=610,
    ),
    Product(
        id="potato",
        name="Картофель",
        storage="обычное",
        shelf_life_days=45,
        base_price_rub=55,
        base_daily_demand=700,
    ),
    Product(
        id="grains",
        name="Крупы",
        storage="обычное",
        shelf_life_days=180,
        base_price_rub=120,
        base_daily_demand=300,
    ),
    Product(
        id="pasta",
        name="Макароны",
        storage="обычное",
        shelf_life_days=180,
        base_price_rub=115,
        base_daily_demand=320,
    ),
    Product(
        id="sugar",
        name="Сахар",
        storage="обычное",
        shelf_life_days=365,
        base_price_rub=90,
        base_daily_demand=260,
    ),
    Product(
        id="flour",
        name="Мука",
        storage="обычное",
        shelf_life_days=180,
        base_price_rub=80,
        base_daily_demand=240,
    ),
    Product(
        id="oil",
        name="Растительное масло",
        storage="обычное",
        shelf_life_days=180,
        base_price_rub=160,
        base_daily_demand=260,
    ),
    Product(
        id="tea",
        name="Чай",
        storage="обычное",
        shelf_life_days=365,
        base_price_rub=210,
        base_daily_demand=180,
    ),
    Product(
        id="coffee",
        name="Кофе",
        storage="обычное",
        shelf_life_days=365,
        base_price_rub=360,
        base_daily_demand=160,
    ),
    Product(
        id="water",
        name="Вода",
        storage="обычное",
        shelf_life_days=365,
        base_price_rub=55,
        base_daily_demand=760,
    ),
    Product(
        id="juice",
        name="Сок",
        storage="обычное",
        shelf_life_days=120,
        base_price_rub=140,
        base_daily_demand=310,
    ),
    Product(
        id="soda",
        name="Газировка",
        storage="обычное",
        shelf_life_days=180,
        base_price_rub=120,
        base_daily_demand=340,
    ),
    Product(
        id="chocolate",
        name="Шоколад",
        storage="обычное",
        shelf_life_days=180,
        base_price_rub=135,
        base_daily_demand=300,
    ),
    Product(
        id="snacks",
        name="Снеки",
        storage="обычное",
        shelf_life_days=180,
        base_price_rub=125,
        base_daily_demand=330,
    ),
    Product(
        id="frozen",
        name="Замороженные продукты",
        storage="морозильник",
        shelf_life_days=90,
        base_price_rub=260,
        base_daily_demand=220,
    ),
    Product(
        id="chemicals",
        name="Бытовая химия",
        storage="обычное",
        shelf_life_days=720,
        base_price_rub=240,
        base_daily_demand=160,
    ),
    Product(
        id="hygiene",
        name="Средства гигиены",
        storage="обычное",
        shelf_life_days=720,
        base_price_rub=210,
        base_daily_demand=180,
    ),
    Product(
        id="baby_food",
        name="Детское питание",
        storage="специальное",
        shelf_life_days=180,
        base_price_rub=190,
        base_daily_demand=150,
    ),
    Product(
        id="pet_food",
        name="Корм для животных",
        storage="обычное",
        shelf_life_days=365,
        base_price_rub=230,
        base_daily_demand=170,
    ),
    Product(
        id="regulated",
        name="Алкоголь/табак",
        storage="обычное",
        shelf_life_days=365,
        base_price_rub=450,
        base_daily_demand=130,
    ),
]

RAW_MATERIALS: list[RawMaterial] = [
    RawMaterial(id="grain", name="Зерно", storage="сухое", base_price_rub=18),
    RawMaterial(
        id="raw_milk", name="Молоко-сырьё", storage="холодильник", base_price_rub=42
    ),
    RawMaterial(id="packaging", name="Упаковка", storage="обычное", base_price_rub=6),
]

PRODUCTION_RECIPES: list[ProductionRecipe] = [
    ProductionRecipe(
        product_id="bread",
        inputs=[
            RecipeInput(raw_material_id="grain", quantity_per_unit=0.7),
            RecipeInput(raw_material_id="packaging", quantity_per_unit=0.05),
        ],
        conversion_cost_rub=12,
    ),
    ProductionRecipe(
        product_id="milk",
        inputs=[
            RecipeInput(raw_material_id="raw_milk", quantity_per_unit=1.08),
            RecipeInput(raw_material_id="packaging", quantity_per_unit=0.08),
        ],
        conversion_cost_rub=9,
    ),
    ProductionRecipe(
        product_id="yogurt",
        inputs=[
            RecipeInput(raw_material_id="raw_milk", quantity_per_unit=0.9),
            RecipeInput(raw_material_id="packaging", quantity_per_unit=0.10),
        ],
        conversion_cost_rub=12,
    ),
]

STARTER_COMPANIES: list[Company] = [
    Company(
        id="player",
        name="Новая компания",
        role=Role.RETAILER,
        region_id="central",
        cash_rub=7_500_000,
    ),
    Company(
        id="npc_producer",
        name="Волжский продукт",
        role=Role.PRODUCER,
        region_id="volga",
        cash_rub=35_000_000,
        is_npc=True,
    ),
    Company(
        id="npc_distributor",
        name="СеверТрансСклад",
        role=Role.DISTRIBUTOR,
        region_id="north",
        cash_rub=22_000_000,
        is_npc=True,
    ),
    Company(
        id="npc_retailer",
        name="Меркурий-ритейл",
        role=Role.RETAILER,
        region_id="south",
        cash_rub=8_000_000,
        is_npc=True,
    ),
    Company(
        id="npc_retailer_aggr",
        name="Дискаунт-маркет",
        role=Role.RETAILER,
        region_id="east_port",
        cash_rub=6_000_000,
        is_npc=True,
        npc_strategy=NpcStrategy.AGGRESSIVE,
    ),
    Company(
        id="npc_producer_prem",
        name="Премиум-фуд",
        role=Role.PRODUCER,
        region_id="volga",
        cash_rub=40_000_000,
        is_npc=True,
        npc_strategy=NpcStrategy.PREMIUM,
    ),
]

INITIAL_ASSETS: list[BusinessAsset] = [
    BusinessAsset(
        id="asset_player_store",
        company_id="player",
        asset_type=AssetType.STORE,
        name="Столичный магазин у дома",
        region_id="central",
        capacity_units_per_day=1_800,
        fixed_cost_rub_per_day=85_000,
        storage_type="смешанное",
        quality_level=1.0,
        store_format=StoreFormat.CONVENIENCE,
    ),
    BusinessAsset(
        id="asset_producer_factory",
        company_id="npc_producer",
        asset_type=AssetType.FACTORY,
        name="Волжский хлебомолочный завод",
        region_id="volga",
        capacity_units_per_day=3_000,
        fixed_cost_rub_per_day=140_000,
        storage_type="производство",
        quality_level=1.0,
        facility_format=FactoryFormat.PLANT.value,
    ),
    BusinessAsset(
        id="asset_distributor_warehouse",
        company_id="npc_distributor",
        asset_type=AssetType.WAREHOUSE,
        name="Северный распределительный склад",
        region_id="north",
        capacity_units_per_day=4_000,
        fixed_cost_rub_per_day=45_000,
        storage_type="смешанное",
        quality_level=1.0,
        facility_format=WarehouseFormat.CENTER.value,
    ),
    BusinessAsset(
        id="asset_npc_retailer_store",
        company_id="npc_retailer",
        asset_type=AssetType.STORE,
        name="Магазин «Меркурий» на юге",
        region_id="south",
        capacity_units_per_day=1_800,
        fixed_cost_rub_per_day=85_000,
        storage_type="смешанное",
        quality_level=1.0,
        store_format=StoreFormat.CONVENIENCE,
    ),
    BusinessAsset(
        id="asset_npc_aggr_store",
        company_id="npc_retailer_aggr",
        asset_type=AssetType.STORE,
        name="Дискаунт «Копейка» в порту",
        region_id="east_port",
        capacity_units_per_day=1_800,
        fixed_cost_rub_per_day=75_000,
        storage_type="смешанное",
        quality_level=1.0,
        store_format=StoreFormat.CONVENIENCE,
    ),
    BusinessAsset(
        id="asset_npc_prem_factory",
        company_id="npc_producer_prem",
        asset_type=AssetType.FACTORY,
        name="Премиум-цех на Волге",
        region_id="volga",
        capacity_units_per_day=2_500,
        fixed_cost_rub_per_day=125_000,
        storage_type="производство",
        quality_level=1.0,
        facility_format=FactoryFormat.PLANT.value,
    ),
]

INITIAL_INVENTORIES: dict[str, dict[str, int]] = {
    "player": {
        "bread": 740,
        "milk": 620,
        "eggs": 410,
        "water": 650,
        "vegetables": 540,
    },
    "npc_producer": {
        "bread": 4_000,
        "milk": 3_500,
        "eggs": 2_000,
        "water": 5_000,
    },
    "npc_distributor": {
        "bread": 1_200,
        "milk": 1_000,
        "water": 2_500,
    },
    "npc_retailer": {
        "bread": 800,
        "milk": 700,
        "eggs": 400,
        "water": 600,
    },
    "npc_retailer_aggr": {
        "bread": 900,
        "milk": 750,
        "water": 700,
        "eggs": 350,
    },
    "npc_producer_prem": {
        "bread": 3_000,
        "milk": 2_500,
        "yogurt": 1_500,
    },
}

INITIAL_RAW_INVENTORIES: dict[str, dict[str, float]] = {
    "npc_producer": {
        "grain": 6_000.0,
        "raw_milk": 5_400.0,
        "packaging": 1_200.0,
    },
    "npc_producer_prem": {
        "grain": 4_500.0,
        "raw_milk": 4_000.0,
        "packaging": 900.0,
    },
}

# season 1=spring, 2=summer, 3=autumn, 4=winter; day → season = (day // 7) % 4 + 1
SEASONAL_DEMAND: dict[int, dict[str, float]] = {
    1: {  # весна
        "water": 1.15,
        "juice": 1.10,
        "soda": 1.10,
        "fruits": 1.20,
        "vegetables": 1.10,
        "chocolate": 0.90,
        "meat": 0.95,
    },
    2: {  # лето
        "water": 1.40,
        "soda": 1.35,
        "juice": 1.25,
        "fruits": 1.40,
        "vegetables": 1.25,
        "ice_cream": 1.80,  # нет в FMCG-матрице, безопасно игнорируется
        "tea": 0.80,
        "coffee": 0.85,
        "meat": 0.90,
        "frozen": 1.20,
    },
    3: {  # осень
        "vegetables": 1.30,
        "fruits": 1.25,
        "potato": 1.20,
        "juice": 1.10,
        "grains": 1.10,
        "water": 0.85,
        "soda": 0.85,
    },
    4: {  # зима
        "meat": 1.25,
        "sausage": 1.15,
        "fish": 1.15,
        "tea": 1.35,
        "coffee": 1.25,
        "chocolate": 1.20,
        "frozen": 1.15,
        "water": 0.70,
        "soda": 0.75,
        "vegetables": 0.80,
        "fruits": 0.85,
    },
}

BANKS: list[Bank] = [
    Bank(
        id="steady_bank",
        name="Надёжный банк",
        description="Низкая ставка, строгий лимит и осторожный скоринг.",
        annual_rate=0.16,
        max_loan_rub=30_000_000,
        risk_appetite=0.35,
    ),
    Bank(
        id="growth_bank",
        name="Банк развития",
        description="Средняя ставка и хорошие лимиты для расширения бизнеса.",
        annual_rate=0.22,
        max_loan_rub=60_000_000,
        risk_appetite=0.65,
    ),
    Bank(
        id="risk_bank",
        name="Риск-капитал банк",
        description="Высокая ставка, но готов кредитовать агрессивный рост.",
        annual_rate=0.34,
        max_loan_rub=100_000_000,
        risk_appetite=0.95,
    ),
]
